### ISSUE TITLE
Create and flesh out methods for Lobby Class

### ISSUE THREAD

**Issue by RileyChampion** [Ji-Justin/TwoRoomsAndABoom-WebApp#12]
Lobby class (if they have any) need basic methods added and developed allowing them to interact with other classes within the server. Please do appropriate testing as well

- This will need to handle creation of multiple instances of a Lobby allowing for the server to handle different instances of the game

**Comment by Ji-Justin** [comment]
start game method
add to list of players when connected method
kick player method
add/remove role method
transfer host method
add ready player method
remove ready player method
toggle bury method
