### ISSUE TITLE
Install and implement Springboot Websocket

### ISSUE THREAD

**Issue by Ji-Justin** [Ji-Justin/TwoRoomsAndABoom-WebApp#14]
Implement websocket for users to connect to each other

**Comment by RileyChampion** [comment]
https://spring.io/guides/gs/messaging-stomp-websocket

**Comment by Ji-Justin** [comment]
https://medium.com/@dragonblade9x/making-a-multiplayer-web-game-with-websocket-that-can-be-scalable-to-millions-of-users-923cc8bd4d3b
